# Generated by Django 3.2.5 on 2021-08-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='creation_date',
        ),
        migrations.AddField(
            model_name='task',
            name='ending_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
