# Generated by Django 3.2.5 on 2021-08-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importance',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Normal'),
        ),
    ]
