# Generated by Django 3.2.5 on 2022-01-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='jd',
            field=models.DateField(blank=True, null=True),
        ),
    ]
