# Generated by Django 3.2.5 on 2021-08-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210806_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creation_date',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='task',
            name='ending_date',
            field=models.DateTimeField(null=True),
        ),
    ]
