# Generated by Django 3.2.5 on 2021-08-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210806_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['ending_date']},
        ),
    ]
