# Generated by Django 3.2.5 on 2022-02-23 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_jd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='jd',
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='ending_date',
            field=models.DateField(null=True),
        ),
    ]
